## CREATING A VIRTUAL ENV
python -m venv venv

## activating the virtual env
venv\Scripts\activate

## starting the fastapi server
uvicorn app.main:app --reload

## sync requiremnts with requirements.txt
pip freeze > requirements.txt